### ISSUE TITLE
Glitch: player sometimes gets spawn at unplayable location

### ISSUE THREAD

**Issue by hoangdesu** [andrewwoan/PSU-VR#5]
![image](https://github.com/andrewwoan/PSU-VR/assets/38454021/9122ecc9-b7e2-47aa-a626-7891f4efb376)

Sometimes player gets spawn at unplayable location. Tested on multiple devices

**Comment by andrewwoan** [comment]
Oh yeah, this is usually an issue with device performance issues. Also the URL in the photo is wrong, it should be this one: https://psu-vr.herokuapp.com/

**Comment by hoangdesu** [comment]
Thank you. This is such a work of art

**Comment by andrewwoan** [comment]
Np, glad you like it!!!
